core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('login/', LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import ProductHomeView, ProductListView, ProductDetailView

app_name = 'products'


urlpatterns = [
    
    path('', ProductHomeView.as_view(), name='home'),
    path('category/<int:id>/', ProductListView.as_view(), name='category_products'),
    path('<int:id>/detail/', ProductDetailView.as_view(), name='product_detail'),
    
    
]

users/urls.py
from django.urls import path
from .views import UserSignupView

app_name = 'users'


urlpatterns = [
    path('signup/', UserSignupView.as_view(), name='signup'),
]

products/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericRelation
from hitcount.models import HitCountMixin, HitCount

# Create your models here.


class Category(models.Model):
	title = models.CharField(max_length=50, blank=False, null=False)
	image = models.ImageField(upload_to='categories', blank=True, null=True)

	def __str__(self):
		return self.title


class Product(models.Model, HitCountMixin):
	name = models.CharField(max_length=50, blank=False, null=False)
	image = models.ImageField(upload_to='products', blank=True, null=True)
	category = models.ForeignKey(Category, on_delete=models.CASCADE)
	hit_count_generic = GenericRelation(
		HitCount, object_id_field='object_pk',
        related_query_name='hit_count_generic_relation'
    )
	
	@property
	def current_hit_count(self):
		return self.hit_count.hits
		
	def __str__(self):
		return self.name

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.validators import MinLengthValidator
from django.core.exceptions import ValidationError
import re



def check_uppercase(value):
	if not re.findall('[A-Z]', value):
		raise ValidationError('Password need at least one uppercase letter.')
	return value


def check_lowercase(value):
	if not re.findall('[a-z]', value):
		raise ValidationError('Password need at least one lowercase letter.')
	return value


def check_firstdigit(value):
	if value[0].isdigit():
		raise ValidationError('First digit must not be a digit')
	return value


class UserSignupForm(UserCreationForm):
	username = forms.CharField(
		widget=forms.TextInput(attrs={'class': 'form-control', 'Placeholder': 'Username'})
	)
	email = forms.EmailField(
		widget=forms.TextInput(attrs={'class': 'form-control', 'Placeholder': 'Email'})
	)
	password1 = forms.CharField(
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'Placeholder': 'password'}),
		validators=[MinLengthValidator(8), check_uppercase, check_lowercase, check_firstdigit]
	)
	password2 = forms.CharField(
		widget=forms.PasswordInput(attrs={'class': 'form-control', 'Placeholder': 'confirm password'})
	)

	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

products/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from hitcount.views import HitCountDetailView

from .models import Category, Product

class ProductHomeView(LoginRequiredMixin, ListView):
	template_name = 'products/home.html'
	model = Category


class ProductListView(LoginRequiredMixin, ListView):
	template_name = 'products/category-products-list.html'
	model = Product

	def get_context_data(self, **kwargs):
		# import pdb; pdb.set_trace();

		context = super().get_context_data(**kwargs)
		categories = Category.objects.all()
		context['categories'] = categories
		return context

	def get_queryset(self):
		cat_id = self.kwargs.get('id')
		qs = Product.objects.filter(category=cat_id)
		return qs



class ProductDetailView(HitCountDetailView):
	template_name = 'products/product_detail.html'
	model = Product
	count_hit = True

	def get_context_data(self, **kwargs):
		# import pdb; pdb.set_trace();

		context = super().get_context_data(**kwargs)
		categories = Category.objects.all()
		context['categories'] = categories
		return context

	def get_object(self):
		pk = self.kwargs.get('id')
		obj = Product.objects.get(id=pk)
		return obj

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView
from .forms import UserSignupForm


class UserSignupView(CreateView):
	form_class = UserSignupForm
	template_name = 'users/register.html'
	success_url = reverse_lazy('home')

core/templates/includes/header.html
<header class="p-3 bg-dark text-white">
<div class="container">
<div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
<a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
  <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
</a>

<ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
  <li><a href="{% url 'home' %}" class="nav-link px-2 text-secondary">Home</a></li>
  {% if request.user.is_authenticated %}
    <li><a href="{% url 'products:home' %}" class="nav-link px-2 text-white">Products</a></li>
  {% endif %}
</ul>


<div class="text-end">
    
    {% if not request.user.is_authenticated %}
        <a type="button" href="#" class="btn btn-outline-light me-2" data-bs-toggle="modal" data-bs-target="#loginModal">Login</a>
        <a href="{% url 'users:signup' %}" class="btn btn-warning">Sign-up</a>
    {% else %}
        <a href="{% url 'logout' %}" class="btn btn-outline-light me-2">Logout</a>
    {% endif %}
</div>
</div>
</div>
</header>

core/templates/includes/login-modal.html
<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="LoginModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    
    <form method="post" action="{% url 'login' %}">
      {% csrf_token %}
    
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">iTQAN Login</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      
      <div class="modal-body">

          <p>
            <label for="id_username">Username:</label>
            <input type="text" name="username" class="form-control" placeholder="Username" autofocus="" required="" id="id_username">
          </p>
          <p>
            <label for="id_password1">Password:</label>
            <input type="password" name="password" class="form-control" placeholder="password" required="" id="id_password">
          </p>


      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Login</button>
      </div>

    </div>

    </form>


  </div>
</div>

core/templates/index.html
{% extends 'layouts/base.html' %}
{% load static %}

    {% block page_style %}
        <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endblock page_style %}


{% block base %}
    
    {% block header %}
        {% include 'includes/header.html' %}
    {% endblock header %}
    {% block content %}
        <h1>Hello</h1>
    {% endblock content %}
    

{% endblock base %}

{% block pagejs %}
{% endblock pagejs %}

core/templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="{% static 'dist/css/bootstrap.min.css' %}" rel="stylesheet">

        {% block page_style %}
        {% endblock page_style %}

        <title>iTQAN Task {{title}}</title>
    </head>
    <body class="bg-secondary">
        {% block base %}
        {% endblock base %}


    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{% static 'dist/js/bootstrap.bundle.min.js' %}"></script>

    {% block pagejs %}
    {% endblock pagejs %}
    </body>
    {% if not request.user.is_authenticated %}
        {% include 'includes/login-modal.html' %}
    {% endif %}
</html>

products/templates/products/category-products-list.html
{% extends 'products/home.html' %}

{% block content %}
    
    <div class="container">
    	<div class="row m-5">
            <div class="col-md-6 offset-3">
                {% include 'products/partials/category-slide.html' %}
            </div>
        </div>
        <div class="row m-5"></div>

        <div class="row">
            <h1>{{ title }}</h1>
            {% for product in object_list %}
                <div class="col-md-3">
                	<a href="{% url 'products:product_detail' id=product.pk %}">
	                    <div class="card">
	                        
	                        {% if product.image %}
	                        	<img src="{{ product.image.url }}" class="card-img-top" alt="...">
	                        {% endif %}
	                        <div class="card-footer">
	                            <h3 class="card-title text-center">{{ product.name }}</h3>
	                        </div>
	                        
	                    </div>
                	</a>
                </div>
            {% empty %}
            <h1>No Products Added</h1>
            {% endfor %}
        </div>
    </div>
    
{% endblock content %}

products/templates/products/home.html
{% extends 'index.html' %}
{% load static %}


{% block content %}
    
    <div class="container">
        <div class="row">
            <h1>Categories</h1>
            {% for category in object_list %}
                <div class="col-md-3">
                    <div class="card">
                        {% if category.image %}
                        <img src="{{ category.image.url }}" class="card-img-top" alt="...">
                        {% endif %}
                        <div class="card-footer">
                            <a href="{% url 'products:category_products' id=category.pk %}">
                                <h3 class="card-title text-center">{{ category.title }}</h3>
                            </a>
                        </div>
                        
                    </div>
                </div>
            {% endfor %}
            
        </div>
    </div>
    
{% endblock content %}

products/templates/products/partials/category-card.html
<div class="card bg-dark text-white">
    <img src="{{ category.image.url }}" class="card-img" alt="...">
        <div class="card-img-overlay">
        <h5 class="card-title">{{ category.title }}</h5>
        <p class="card-text">{{ category.title }}</p>
    </div>
</div>

products/templates/products/partials/category-slide.html
<div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
    
    <div class="carousel-inner">
        {% for category in categories %}
        
        <div class="carousel-item {% if forloop.first %} active {% endif %}">
            <a href="{% url 'products:category_products' id=category.pk %}">
                <img src="{{ category.image.url }}" class="d-block w-100" alt="">
            </a>
        </div>
        {% endfor %}
        
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>

</div>

products/templates/products/product_detail.html
{% extends 'products/home.html' %}

{% block content %}

    <div class="container m-5">
        <div class="row m-5">
            <div class="col-md-6 offset-3">
                {% include 'products/partials/category-slide.html' %}
            </div>
        </div>

        <div class="row m-5"></div>
        
        <div class="row mb-2">
            <div class="col-md-6">
                <div class="card" style="width: 18rem;">
                    {% if object.image %}
                    <img src="{{ object.image.url }}" class="card-img-top" alt="...">
                    {% endif %}
                  <div class="card-body">
                    <p class="card-text">{{ object.name }}</p>
                  </div>
                </div>
            </div>

            
            
        </div>
    </div>
    
{% endblock content %}

users/templates/users/register.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block page_style %}
    <link href="{% static 'css/signup.css' %}" rel="stylesheet">
{% endblock page_style %}

{% block base %}
<main class="card form-signin">
    <div class="card-body">
        <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
    
            <h1 class="h3 mb-3 fw-normal">Please sign up</h1>

            <div class="form-floating">
                {{ form.as_p }}
            </div>
            <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
        
        </form>
    </div>
</main>
{% endblock base %}